In [1]:
#convolutional layer

import numpy as np

image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])

kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

output = np.zeros((3, 3))
 
for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("After multiplying:")
        print(region * kernel)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)


Region (0,0):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
After multiplying:
[[   0    0    0]
 [   0    0 -255]
 [   0    0 -255]]
Sum = -510
----------------------------------------
Region (0,1):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
After multiplying:
[[   0    0    0]
 [ 255    0 -255]
 [ 255    0 -255]]
Sum = 0
----------------------------------------
Region (0,2):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
After multiplying:
[[  0   0   0]
 [255   0   0]
 [255   0   0]]
Sum = 510
----------------------------------------
Region (1,0):
[[  0 255 255]
 [  0 255 255]
 [  0 255 255]]
After multiplying:
[[   0    0 -255]
 [   0    0 -255]
 [   0    0 -255]]
Sum = -765
----------------------------------------
Region (1,1):
[[255 255 255]
 [255 255 255]
 [255 255 255]]
After multiplying:
[[ 255    0 -255]
 [ 255    0 -255]
 [ 255    0 -255]]
Sum = 0
----------------------------------------
Region (1,2):
[[255 255   0]
 [255 255   0]
 [255 255   0]]
After multiplying:
[[255  

In [2]:
#stride useage
import numpy as np

image = np.arange(25).reshape(5,5)
kernel = np.ones((3,3))

stride = 2
output_size = ((5 - 3)//stride) + 1
output = np.zeros((output_size, output_size))

for i in range(0, 5-2, stride):
    for j in range(0, 5-2, stride):
        region = image[i:i+3, j:j+3]
        output[i//stride, j//stride] = np.sum(region * kernel)

print(output)


[[ 54.  72.]
 [144. 162.]]


In [7]:
#stride
import numpy as np

image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])

kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])
stride=2
output = np.zeros((2, 2))

for i in range(0,5-2,stride):
    for j in range(0,5-2,stride):
        region = image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i//stride, j//stride] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("After multiply:")
        print(region * kernel)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)


Region (0,0):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
After multiply:
[[   0    0    0]
 [   0    0 -255]
 [   0    0 -255]]
Sum = -510
----------------------------------------
Region (0,2):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
After multiply:
[[  0   0   0]
 [255   0   0]
 [255   0   0]]
Sum = 510
----------------------------------------
Region (2,0):
[[  0 255 255]
 [  0 255 255]
 [  0   0   0]]
After multiply:
[[   0    0 -255]
 [   0    0 -255]
 [   0    0    0]]
Sum = -510
----------------------------------------
Region (2,2):
[[255 255   0]
 [255 255   0]
 [  0   0   0]]
After multiply:
[[255   0   0]
 [255   0   0]
 [  0   0   0]]
Sum = 510
----------------------------------------
Final feature map:
[[-510.  510.]
 [-510.  510.]]


In [9]:
#padding
import numpy as np

image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])

kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])


padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

output = np.zeros((5, 5)) 

for i in range(5):
    for j in range(5):
        region = padded_image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)



Region (0,0):
[[  0   0   0]
 [  0   0   0]
 [  0   0 255]]
Sum = -255
----------------------------------------
Region (0,1):
[[  0   0   0]
 [  0   0   0]
 [  0 255 255]]
Sum = -255
----------------------------------------
Region (0,2):
[[  0   0   0]
 [  0   0   0]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (0,3):
[[  0   0   0]
 [  0   0   0]
 [255 255   0]]
Sum = 255
----------------------------------------
Region (0,4):
[[  0   0   0]
 [  0   0   0]
 [255   0   0]]
Sum = 255
----------------------------------------
Region (1,0):
[[  0   0   0]
 [  0   0 255]
 [  0   0 255]]
Sum = -510
----------------------------------------
Region (1,1):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
Sum = -510
----------------------------------------
Region (1,2):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (1,3):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
Sum = 510
----------------------------------------
R

In [15]:
#ReLU function

import numpy as mp
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])
kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

output = np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        region = padded_image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)
def relu(x):
    return np.maximum(0,x)
print("after relu:")
print(relu(output))


Region (0,0):
[[  0   0   0]
 [  0   0   0]
 [  0   0 255]]
Sum = -255
----------------------------------------
Region (0,1):
[[  0   0   0]
 [  0   0   0]
 [  0 255 255]]
Sum = -255
----------------------------------------
Region (0,2):
[[  0   0   0]
 [  0   0   0]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (0,3):
[[  0   0   0]
 [  0   0   0]
 [255 255   0]]
Sum = 255
----------------------------------------
Region (0,4):
[[  0   0   0]
 [  0   0   0]
 [255   0   0]]
Sum = 255
----------------------------------------
Region (1,0):
[[  0   0   0]
 [  0   0 255]
 [  0   0 255]]
Sum = -510
----------------------------------------
Region (1,1):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
Sum = -510
----------------------------------------
Region (1,2):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (1,3):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
Sum = 510
----------------------------------------
R

In [19]:
#pooling

import numpy as mp
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])
kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

output = np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        region = padded_image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)
def relu(x):
    return np.maximum(0,x)
print("after relu:")
print(relu(output))

feature_map=relu(output)

def max_pooling(feature_map, pool_size=2, stride=2):
    h, w = feature_map.shape
    out_h = (h - pool_size) // stride + 1
    out_w = (w - pool_size) // stride + 1
    pooled = np.zeros((out_h, out_w))
    
    for i in range(0, h - pool_size + 1, stride):
        for j in range(0, w - pool_size + 1, stride):
            window = feature_map[i:i+pool_size, j:j+pool_size]
            pooled[i//stride, j//stride] = np.max(window)
    
    return pooled
pooled_output = max_pooling(feature_map)
print("After 2x2 Max Pooling:")
print(pooled_output)


Region (0,0):
[[  0   0   0]
 [  0   0   0]
 [  0   0 255]]
Sum = -255
----------------------------------------
Region (0,1):
[[  0   0   0]
 [  0   0   0]
 [  0 255 255]]
Sum = -255
----------------------------------------
Region (0,2):
[[  0   0   0]
 [  0   0   0]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (0,3):
[[  0   0   0]
 [  0   0   0]
 [255 255   0]]
Sum = 255
----------------------------------------
Region (0,4):
[[  0   0   0]
 [  0   0   0]
 [255   0   0]]
Sum = 255
----------------------------------------
Region (1,0):
[[  0   0   0]
 [  0   0 255]
 [  0   0 255]]
Sum = -510
----------------------------------------
Region (1,1):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
Sum = -510
----------------------------------------
Region (1,2):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (1,3):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
Sum = 510
----------------------------------------
R

In [29]:
#flattening

import numpy as mp
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])
kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

output = np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        region = padded_image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value

        print(f"Region ({i},{j}):")
        print(region)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)
def relu(x):
    return np.maximum(0,x)
print("after relu:")
print(relu(output))

feature_map=relu(output)

def max_pooling(feature_map, pool_size=2, stride=2):
    h, w = feature_map.shape
    out_h = (h - pool_size) // stride + 1
    out_w = (w - pool_size) // stride + 1
    pooled = np.zeros((out_h, out_w))
    
    for i in range(0, h - pool_size + 1, stride):
        for j in range(0, w - pool_size + 1, stride):
            window = feature_map[i:i+pool_size, j:j+pool_size]
            pooled[i//stride, j//stride] = np.max(window)
    
    return pooled
pooled_output = max_pooling(feature_map)
print("After 2x2 Max Pooling:")
print(pooled_output)

flattening= pooled_output.flatten()
print("after flattening:", flattening)

Region (0,0):
[[  0   0   0]
 [  0   0   0]
 [  0   0 255]]
Sum = -255
----------------------------------------
Region (0,1):
[[  0   0   0]
 [  0   0   0]
 [  0 255 255]]
Sum = -255
----------------------------------------
Region (0,2):
[[  0   0   0]
 [  0   0   0]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (0,3):
[[  0   0   0]
 [  0   0   0]
 [255 255   0]]
Sum = 255
----------------------------------------
Region (0,4):
[[  0   0   0]
 [  0   0   0]
 [255   0   0]]
Sum = 255
----------------------------------------
Region (1,0):
[[  0   0   0]
 [  0   0 255]
 [  0   0 255]]
Sum = -510
----------------------------------------
Region (1,1):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
Sum = -510
----------------------------------------
Region (1,2):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (1,3):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
Sum = 510
----------------------------------------
R

In [31]:
import numpy as mp
image = np.array([
    [0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 255, 255, 255, 0],
    [0, 0, 0, 0, 0]
])
kernel = np.array([
    [ 1,  0, -1],
    [ 1,  0, -1],
    [ 1,  0, -1]
])

padded_image = np.pad(image, pad_width=1, mode='constant', constant_values=0)

output = np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        region = padded_image[i:i+3, j:j+3]
        value = np.sum(region * kernel)
        output[i, j] = value
        print(f"Region ({i},{j}):")
        print(region)
        print("Sum =", value)
        print("-" * 40)

print("Final feature map:")
print(output)
def relu(x):
    return np.maximum(0,x)
print("after relu:")
print(relu(output))

feature_map=relu(output)

def max_pooling(feature_map, pool_size=2, stride=2):
    h, w = feature_map.shape
    out_h = (h - pool_size) // stride + 1
    out_w = (w - pool_size) // stride + 1
    pooled = np.zeros((out_h, out_w))
    
    for i in range(0, h - pool_size + 1, stride):
        for j in range(0, w - pool_size + 1, stride):
            window = feature_map[i:i+pool_size, j:j+pool_size]
            pooled[i//stride, j//stride] = np.max(window)
    
    return pooled
pooled_output = max_pooling(feature_map)
print("After 2x2 Max Pooling:")
print(pooled_output)

kernel2 = np.array([
    [1,  1,  1],
    [0,  0,  0],
    [-1, -1, -1]
])

# padding pooled output
padded_pooled = np.pad(pooled_output, pad_width=1, mode='constant')

output2 = np.zeros_like(pooled_output)

for i in range(pooled_output.shape[0]):
    for j in range(pooled_output.shape[1]):
        region = padded_pooled[i:i+3, j:j+3]
        output2[i, j] = np.sum(region * kernel2)


print("After Conv Layer 2:")
print(output2)

flattening = output2.flatten()
print("After flattening:", flattening)


Region (0,0):
[[  0   0   0]
 [  0   0   0]
 [  0   0 255]]
Sum = -255
----------------------------------------
Region (0,1):
[[  0   0   0]
 [  0   0   0]
 [  0 255 255]]
Sum = -255
----------------------------------------
Region (0,2):
[[  0   0   0]
 [  0   0   0]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (0,3):
[[  0   0   0]
 [  0   0   0]
 [255 255   0]]
Sum = 255
----------------------------------------
Region (0,4):
[[  0   0   0]
 [  0   0   0]
 [255   0   0]]
Sum = 255
----------------------------------------
Region (1,0):
[[  0   0   0]
 [  0   0 255]
 [  0   0 255]]
Sum = -510
----------------------------------------
Region (1,1):
[[  0   0   0]
 [  0 255 255]
 [  0 255 255]]
Sum = -510
----------------------------------------
Region (1,2):
[[  0   0   0]
 [255 255 255]
 [255 255 255]]
Sum = 0
----------------------------------------
Region (1,3):
[[  0   0   0]
 [255 255   0]
 [255 255   0]]
Sum = 510
----------------------------------------
R